### ISSUE TITLE
Missing scene files

### ISSUE THREAD

**Issue by ashikns** [Madison-SDC/UltimateTicTacToe#1]
There are no *.unity scene files in the scenes folder

**Comment by mark-wiemer** [comment]
This repository doesn't necessarily contain every file in the project on my local directory. This is because committing binary files (.exe, .unity, etc.) doesn't really help anybody understand the project. Binary files are unintelligible by definition. Because of this, merge conflicts, reassigning commits, and other git issues around binary files are almost impossible to reliably attain: _you'd have to understand every bit of the binary file to know which version is newer or older_, which can't be expected.

For this reason, binary files are excluded from commits and repositories in general, as directed by the .gitignore file.

If you want to access scenes and actually run the code, check out the releases, and download, unzip, and run the files there.

**Comment by mark-wiemer** [comment]
More information about why committing binaries is bad can be found here: https://development.robinwinslow.uk/2013/06/11/dont-ever-commit-binary-files-to-git/

I actually initially _did_ include binaries, not knowing the consequences. I'm not invested enough to rewrite the history of this project, so they remain in the history, and this repository is bloated due to my laziness. Maybe I'll get around to it one day...

**Comment by ashikns** [comment]
.unity scene files are text serialized, meaning they are text files essentially. This might only be for pro licenses though. Anyway I respect your decision, thanks for the reply
